version: '3.9'

services:
  bot:
    build: .
    #user: 1001:1001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    working_dir: /bot
    volumes:
      - .:/bot:delegated
    command: pnpm start
